services:
  - type: web
    name: task-api
    runtime: node
    buildCommand: npm install && npx prisma generate && npm run bundle:docs
    startCommand: npm run migrate:deploy && npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
