openapi: 3.0.3
info:
  title: Task API
  version: 1.0.0
  description: A simple API for managing tasks
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://your-app.onrender.com
    description: Production server
paths:
  /tasks:
    get:
      summary: Get all tasks
      description: Retrieve a list of all tasks
      tags:
        - Tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      description: Create a new task with title and completion status
      tags:
        - Tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
  /tasks/{id}:
    get:
      summary: Get a task by ID
      description: Retrieve a single task by its unique ID
      tags:
        - Tasks
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the task
          schema:
            type: integer
            minimum: 1
          example: 1
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                title: Buy groceries
                completed: false
        '400':
          description: Validation error (invalid ID format)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
              example:
                error: Validation failed
                details:
                  - ID must be a number
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundError'
              example:
                error: Task not found
components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the task
          example: 1
        title:
          type: string
          description: The title of the task
          example: Buy groceries
        completed:
          type: boolean
          nullable: true
          description: Whether the task is completed
          example: false
      required:
        - id
        - title
    TaskInput:
      type: object
      properties:
        title:
          type: string
          minLength: 3
          maxLength: 100
          description: The title of the task (3-100 characters)
          example: Complete the documentation
        completed:
          type: boolean
          description: Whether the task is completed
          example: false
      required:
        - title
    ValidationError:
      type: object
      properties:
        error:
          type: string
          example: Validation failed
        details:
          type: array
          items:
            type: string
          example:
            - Title is required
            - Title must be at least 3 and at most 100 characters
      required:
        - error
        - details
    NotFoundError:
      type: object
      properties:
        error:
          type: string
          example: Task not found
      required:
        - error
